### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by elfonochasis** [Futil/foundry-mausritter#5]
Hello,

I want to translate the sheet but en.json is empty. Do you bring up use it? 

Thanks! Greetings!

**Comment by Futil** [comment]
I haven't been using the language architecture yet while I've been building
the base system. It's on my docket for 0.1.0, but since it seems a lot more
people are interested in the system now I'll set that as the next feature
to focus. I'll have the language architecture set up by Saturday, and then
folks can work to translate it!

**Comment by elfonochasis** [comment]
Well done!! Thanks you so much!

**Comment by Futil** [comment]
Okay, localization support *should* now be baked into Mausritter, with the exception of the built in compendiums. Let me know if there is anything I missed.

**Comment by brunocalado** [comment]
Brazilian Portuguese file
[pt-br.zip](https://github.com/Futil/foundry-mausritter/files/5740328/pt-br.zip)

**Comment by brunocalado** [comment]
I can't see the translation. Should I do something special?

**Comment by Futil** [comment]
Strange, it seems to be working for me. It should look like this in your system settings: 
![image](https://user-images.githubusercontent.com/982251/103147020-f675e300-470d-11eb-9b7b-be54b6f80dc3.png)

**Comment by brunocalado** [comment]
I know what happened...
![image](https://user-images.githubusercontent.com/4999783/103151826-5301ee00-4760-11eb-8c10-12d760049f22.png)

**Comment by brunocalado** [comment]
Can you change to Português (Brasil)?

**Comment by brunocalado** [comment]
Update with the last strings.

[pt-br.zip](https://github.com/Futil/foundry-mausritter/files/5743099/pt-br.zip)

**Comment by Futil** [comment]
Got it, changing it now!

**Comment by struckyCZ** [comment]
Hey,
since the official Czech version has just been released, I've made a translation based on the official wordings.
Also how would I go about translating the compendiums without directly messing with the core of your system module?
Also here is the string for system.json
`{
      "lang": "cs",
      "name": "Čeština (Czech)",
      "path": "lang/cs.json"
    }`
[cs.zip](https://github.com/Futil/foundry-mausritter/files/9208032/cs.zip)
.
